## Comenzamos con la Actividad 1 de la Guia 2

In [ ]:
options(warn=-1)
install.packages("readxl")
library("readxl")
nombre_excel <- "/content/df_secundario_comun_depurado.xlsx" # Changed to direct path
datos_secundaria_comun <- read_excel(nombre_excel)
head(datos_secundaria_comun)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

  CUE     suborganizacion                           departamento EsPrivada
1 6000934 ESCUELA SECUNDARIA N° 7 CARLOS L. VERGARA DIAMANTE     N
2 6000934 ESCUELA SECUNDARIA N° 7 CARLOS L. VERGARA DIAMANTE     N
3 6000934 ESCUELA SECUNDARIA N° 7 CARLOS L. VERGARA DIAMANTE     N
4 6000934 ESCUELA SECUNDARIA N° 7 CARLOS L. VERGARA DIAMANTE     N
5 6000934 ESCUELA SECUNDARIA N° 7 CARLOS L. VERGARA DIAMANTE     N
6 6000934 ESCUELA SECUNDARIA N° 7 CARLOS L. VERGARA DIAMANTE     N
  anioLectivo curso          Documento Asignatura          NotaPrimerTrimestre
1 2024        1ro Secundaria 24606779  BIOLOGIA            10
2 2024        1ro Secundaria 24606779  FISICA              10
3 2024        1ro Secundaria 24606779  LENGUAS EXTRANJERAS  9
4 2024        1ro Secundaria 24606779  QUIMICA              9
5 2024        1ro Secundaria 24606779  LENGUA Y LITERATURA  8
6 2024        1ro Secundaria 24606779  GEOGRAFIA            6
  NotaSegundoTrimestre NotaTercerTrimestre NotaDiciembre Promedio  Resultado
1 10                   10                  NA            10.000000 Aprobo
2 10                   10                  NA            10.000000 Aprobo
3 10                    8                  NA             9.000000 Aprobo
4 10                   10                  NA             9.666667 Aprobo
5 10                   10                  NA             9.333333 Aprobo
6  7                   10                  NA             7.666667 Aprobo

In [ ]:
library(tidyverse)
distribucion_secundaria_comun <- datos_secundaria_comun %>%
  distinct(Documento, .keep_all = TRUE) %>% # Seleccionar filas únicas por ID_alumno
  count(curso) %>%
  mutate(
    Frecuencia_Relativa = n / sum(n),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100
  )

distribucion_secundaria_comun

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

  curso          n   Frecuencia_Relativa Frecuencia_Porcentual
1 1ro Secundaria 582 0.1955645           19.55645
2 2do Secundaria 548 0.1841398           18.41398
3 3ro Secundaria 503 0.1690188           16.90188
4 4to Secundaria 512 0.1720430           17.20430
5 5to Secundaria 413 0.1387769           13.87769
6 6to Secundaria 418 0.1404570           14.04570

In [ ]:
sum(distribucion_secundaria_comun$n)

[1] 2976

Avanzamos con el analisis:

In [ ]:
# Verificamos la pregunta 1 C

tabla_secundaria_sector <- datos_secundaria_comun %>%
  distinct(suborganizacion, .keep_all = TRUE) %>% # Seleccionar filas únicas por nombre de la institucion
  count(EsPrivada) %>%
  mutate(
    Frecuencia_Relativa = n / sum(n),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100
  )

tabla_secundaria_sector

  EsPrivada n  Frecuencia_Relativa Frecuencia_Porcentual
1 N         14 0.6666667           66.66667
2 S          7 0.3333333           33.33333

## Avanzamos con la actividad 2 de la Guia 2

In [ ]:
# Creamos las tablas de frecuencia para responder la preguntas de la actividad 2.
# empezamos filtrando las materias:

library(dplyr)
datos_matematicas <- datos_secundaria_comun %>%
  filter(Asignatura == "MATEMATICA")
datos_lengua <- datos_secundaria_comun %>%
  filter(Asignatura == "LENGUA Y LITERATURA")
datos_biologia <- datos_secundaria_comun %>%
  filter(Asignatura == "BIOLOGIA")
datos_geografia <- datos_secundaria_comun %>%
  filter(Asignatura == "GEOGRAFIA")
datos_historia <- datos_secundaria_comun %>%
  filter(Asignatura == "HISTORIA")
datos_educacion_fisica <- datos_secundaria_comun %>%
  filter(Asignatura == "EDUCACION FISICA")
datos_lenguas_extranjeras <- datos_secundaria_comun %>%
  filter(Asignatura == "LENGUAS EXTRANJERAS")

In [ ]:
table(datos_secundaria_comun$Asignatura)

           BIOLOGIA    EDUCACION FISICA              FISICA    FISICA Y QUIMICA
               2576                2848                1019                1551
          GEOGRAFIA            HISTORIA LENGUA Y LITERATURA LENGUAS EXTRANJERAS
               2927                2919                2929                2905
         MATEMATICA             QUIMICA
               2932                1012

In [ ]:
# Calculo de estadisticos:

calcular_estadisticos <- function(df, columna) {
  # Asegurarse de que las bibliotecas necesarias estén instaladas y cargadas
  if (!require("modeest")) install.packages("modeest")
  library(modeest)
  if (!require("moments")) install.packages("moments")
  library(moments)
  if (!require("knitr")) install.packages("knitr")
  library(knitr)

  # Calcular estadísticos descriptivos
  media <- mean(df[[columna]])
  mediana <- median(df[[columna]])
  moda <- mfv(df[[columna]])
  desvio_estandar <- sd(df[[columna]])
  rango <- max(df[[columna]]) - min(df[[columna]])
  Q1 <- quantile(df[[columna]], 0.25)
  Q3 <- quantile(df[[columna]], 0.75)
  RIQ <- IQR(df[[columna]])
  cv <- (desvio_estandar / media) * 100
  asimetria <- skewness(df[[columna]])
  curtosis_valor <- kurtosis(df[[columna]])

  # Identificar outliers
  limite_inferior <- Q1 - 1.5 * RIQ
  limite_superior <- Q3 + 1.5 * RIQ
  outliers <- df[[columna]][df[[columna]] < limite_inferior | df[[columna]] > limite_superior]

  # Calcular percentil 70 y decil 8
  P70 <- quantile(df[[columna]], 0.70)
  D8 <- quantile(df[[columna]], 0.80)

  # Crear data frame con los estadísticos
  estadisticos <- data.frame(
    Media = media,
    Mediana = mediana,
    Moda = moda,
    Desvio_Estandar = desvio_estandar,
    Rango = rango,
    Q1 = Q1,
    Q3 = Q3,
    RIQ = RIQ,
    CV = cv,
    Asimetria = asimetria,
    Curtosis = curtosis_valor,
    P70 = P70,
    D8 = D8,
    Outliers = paste(head(round(outliers, 1), 5), collapse = ", ")
  )

  # Mostrar la tabla de estadísticos con kable()
  kable(estadisticos)
}

# Calculo de la materia Matematica por años:

In [ ]:
# Dividimos el data set de matematica en años:

# Combinar divisiones en una nueva columna
datos_matematicas_1o <- datos_matematicas %>%
  filter(curso == "1ro Secundaria") %>%
  mutate(division_agrupada = "1er Año")

datos_matematicas_2o <- datos_matematicas %>%
  filter(curso == "2do Secundaria") %>%
  mutate(division_agrupada = "2do Año")

datos_matematicas_3o <- datos_matematicas %>%
  filter(curso == "3ro Secundaria") %>%
  mutate(division_agrupada = "3er Año")

datos_matematicas_4o <- datos_matematicas %>%
  filter(curso == "4to Secundaria") %>%
  mutate(division_agrupada = "4to Año")

datos_matematicas_5o <- datos_matematicas %>%
  filter(curso == "5to Secundaria") %>%
  mutate(division_agrupada = "5to Año")

datos_matematicas_6o <- datos_matematicas %>%
  filter(curso == "6to Secundaria") %>%
  mutate(division_agrupada = "6to Año")

 Ahora debemos por cada año hacer los estudios y tablas correspondientes a la actividad 2 de la Guia 2.

### Matematicas 1er año

In [ ]:
# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_matematicas1 <- datos_matematicas_1o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_matematicas1 <- datos_matematicas1 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_matematicas1)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                1                 0.001727116
2 [3,4)               10                 0.017271157
3 [4,5)               36                 0.062176166
4 [5,6)               78                 0.134715026
5 [6,7)              138                 0.238341969
6 [7,8)              113                 0.195164076
7 [8,9)              108                 0.186528497
8 [9,10]              95                 0.164075993
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.1727116              1
2  1.7271157             11
3  6.2176166             47
4 13.4715026            125
5 23.8341969            263
6 19.5164076            376
7 18.6528497            484
8 16.4075993            579
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.001727116                     0.1727116
2 0.018998273                     1.8998273
3 0.081174439                     8.1174439
4 0.215889465                    21.5889465
5 0.454231434                    45.4231434
6 0.649395509                    64.9395509
7 0.835924007                    83.5924007
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_matematicas_1o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar|    Rango| Q1|       Q3|      RIQ|      CV|  Asimetria| Curtosis| P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|--------:|--:|--------:|--------:|-------:|----------:|--------:|---:|--------:|:--------|
|25% | 7.068509|       7|    6|        1.606799| 7.333333|  6| 8.333333| 2.333333| 22.7318| -0.1195807| 2.254637|   8| 8.666667|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_matematicas_1o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 33.33333
[1] 66.66667
[1] 29.36097

### Matematica 2do año

In [ ]:
# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_matematicas2 <- datos_matematicas_2o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_matematicas2 <- datos_matematicas2 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_matematicas2)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                6                 0.01111111
2 [3,4)               13                 0.02407407
3 [4,5)               63                 0.11666667
4 [5,6)               78                 0.14444444
5 [6,7)              139                 0.25740741
6 [7,8)               91                 0.16851852
7 [8,9)               73                 0.13518519
8 [9,10]              77                 0.14259259
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.111111               6
2  2.407407              19
3 11.666667              82
4 14.444444             160
5 25.740741             299
6 16.851852             390
7 13.518519             463
8 14.259259             540
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01111111                      1.111111
2 0.03518519                      3.518519
3 0.15185185                     15.185185
4 0.29629630                     29.629630
5 0.55370370                     55.370370
6 0.72222222                     72.222222
7 0.85740741                     85.740741
8 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_matematicas_2o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar| Rango|       Q1| Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70|       D8|Outliers |
|:---|--------:|--------:|----:|---------------:|-----:|--------:|--:|--------:|--------:|----------:|--------:|--------:|--------:|:--------|
|25% | 6.701235| 6.333333|    6|        1.751296|     8| 5.333333|  8| 2.666667| 26.13392| -0.0245259| 2.352639| 7.666667| 8.333333|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_matematicas_2o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
7.666667

[1] 42.03704
[1] 57.96296
[1] 23.88889

### Matematicas 3er año

In [ ]:
# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_matematicas3 <- datos_matematicas_3o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_matematicas3 <- datos_matematicas3 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_matematicas3)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                9                 0.018
2 [4,5)               46                 0.092
3 [5,6)               75                 0.150
4 [6,7)              117                 0.234
5 [7,8)               96                 0.192
6 [8,9)               82                 0.164
7 [9,10]              75                 0.150
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.8                    9
2  9.2                   55
3 15.0                  130
4 23.4                  247
5 19.2                  343
6 16.4                  425
7 15.0                  500
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.018                           1.8
2 0.110                          11.0
3 0.260                          26.0
4 0.494                          49.4
5 0.686                          68.6
6 0.850                          85.0
7 1.000                         100.0

In [ ]:
calcular_estadisticos(datos_matematicas_3o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar| Rango|       Q1|       Q3|      RIQ|      CV|  Asimetria| Curtosis| P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|-----:|--------:|--------:|--------:|-------:|----------:|--------:|---:|--------:|:--------|
|25% | 6.889333|       7|    6|        1.646227|     7| 5.666667| 8.083333| 2.416667| 23.8953| -0.0697692| 2.145942|   8| 8.666667|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_matematicas_3o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 36.4
[1] 63.6
[1] 25

### Matematicas 4to año

In [ ]:
# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_matematicas4 <- datos_matematicas_4o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_matematicas4 <- datos_matematicas4 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_matematicas4)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                6                 0.01221996
2 [4,5)               33                 0.06720978
3 [5,6)               62                 0.12627291
4 [6,7)              125                 0.25458248
5 [7,8)               96                 0.19551935
6 [8,9)               92                 0.18737271
7 [9,10]              77                 0.15682281
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.221996               6
2  6.720978              39
3 12.627291             101
4 25.458248             226
5 19.551935             322
6 18.737271             414
7 15.682281             491
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01221996                      1.221996
2 0.07942974                      7.942974
3 0.20570265                     20.570265
4 0.46028513                     46.028513
5 0.65580448                     65.580448
6 0.84317719                     84.317719
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_matematicas_4o, "Promedio")

|    |   Media| Mediana| Moda| Desvio_Estandar| Rango| Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers |
|:---|-------:|-------:|----:|---------------:|-----:|--:|--------:|--------:|--------:|----------:|--------:|---:|--------:|:--------|
|25% | 7.04277|       7|    6|        1.585143|     7|  6| 8.333333| 2.333333| 22.50739| -0.0698203| 2.244387|   8| 8.666667|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_matematicas_4o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 32.99389
[1] 67.00611
[1] 28.10591

### Matematicas 5to año

In [ ]:
# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_matematicas5 <- datos_matematicas_5o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_matematicas5 <- datos_matematicas5 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_matematicas5)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)               9                  0.02205882
2 [4,5)              33                  0.08088235
3 [5,6)              47                  0.11519608
4 [6,7)              86                  0.21078431
5 [7,8)              76                  0.18627451
6 [8,9)              81                  0.19852941
7 [9,10]             76                  0.18627451
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  2.205882               9
2  8.088235              42
3 11.519608              89
4 21.078431             175
5 18.627451             251
6 19.852941             332
7 18.627451             408
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.02205882                      2.205882
2 0.10294118                     10.294118
3 0.21813725                     21.813725
4 0.42892157                     42.892157
5 0.61519608                     61.519608
6 0.81372549                     81.372549
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_matematicas_5o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar| Rango| Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|-----:|--:|--------:|--------:|--------:|----------:|--------:|--------:|--------:|:--------|
|25% | 7.105392|       7|    6|        1.669875|     7|  6| 8.666667| 2.666667| 23.50152| -0.2560994|  2.21355| 8.333333| 8.666667|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_matematicas_5o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 31.61765
[1] 68.38235
[1] 31.61765

### Matematicas 6to año

In [ ]:
# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_matematicas6 <- datos_matematicas_6o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_matematicas6 <- datos_matematicas6 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_matematicas6)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                2                 0.004830918
2 [4,5)               14                 0.033816425
3 [5,6)               28                 0.067632850
4 [6,7)              109                 0.263285024
5 [7,8)               78                 0.188405797
6 [8,9)               88                 0.212560386
7 [9,10]              95                 0.229468599
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.4830918              2
2  3.3816425             16
3  6.7632850             44
4 26.3285024            153
5 18.8405797            231
6 21.2560386            319
7 22.9468599            414
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.004830918                     0.4830918
2 0.038647343                     3.8647343
3 0.106280193                    10.6280193
4 0.369565217                    36.9565217
5 0.557971014                    55.7971014
6 0.770531401                    77.0531401
7 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_matematicas_6o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar| Rango|       Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70| D8|Outliers |
|:---|--------:|--------:|----:|---------------:|-----:|--------:|--------:|--------:|--------:|----------:|--------:|--------:|--:|:--------|
|25% | 7.519324| 7.666667|    6|        1.549481|     7| 6.333333| 8.666667| 2.333333| 20.60665| -0.1610573| 2.274161| 8.333333|  9|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_matematicas_6o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_matematicas_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 22.46377
[1] 77.53623
[1] 38.4058

# Calculo de la materia Lengua por años:

In [ ]:
# Dividimos el data set de matematica en años:

# Combinar divisiones en una nueva columna
datos_lengua_1o <- datos_lengua %>%
  filter(curso == "1ro Secundaria") %>%
  mutate(division_agrupada = "1er Año")

datos_lengua_2o <- datos_lengua %>%
  filter(curso == "2do Secundaria") %>%
  mutate(division_agrupada = "2do Año")

datos_lengua_3o <- datos_lengua %>%
  filter(curso == "3ro Secundaria") %>%
  mutate(division_agrupada = "3er Año")

datos_lengua_4o <- datos_lengua %>%
  filter(curso == "4to Secundaria") %>%
  mutate(division_agrupada = "4to Año")

datos_lengua_5o <- datos_lengua %>%
  filter(curso == "5to Secundaria") %>%
  mutate(division_agrupada = "5to Año")

datos_lengua_6o <- datos_lengua %>%
  filter(curso == "6to Secundaria") %>%
  mutate(division_agrupada = "6to Año")

### Lengua 1er año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_lengua1 <- datos_lengua_1o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_lengua1 <- datos_lengua1 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_lengua1)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                1                 0.001736111
2 [3,4)                6                 0.010416667
3 [4,5)               33                 0.057291667
4 [5,6)               65                 0.112847222
5 [6,7)              132                 0.229166667
6 [7,8)              112                 0.194444444
7 [8,9)              128                 0.222222222
8 [9,10]              99                 0.171875000
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.1736111              1
2  1.0416667              7
3  5.7291667             40
4 11.2847222            105
5 22.9166667            237
6 19.4444444            349
7 22.2222222            477
8 17.1875000            576
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.001736111                     0.1736111
2 0.012152778                     1.2152778
3 0.069444444                     6.9444444
4 0.182291667                    18.2291667
5 0.411458333                    41.1458333
6 0.605902778                    60.5902778
7 0.828125000                    82.8125000
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_lengua_1o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar|    Rango| Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70|       D8|Outliers |
|:---|--------:|--------:|----:|---------------:|--------:|--:|--------:|--------:|--------:|----------:|--------:|--------:|--------:|:--------|
|25% | 7.192708| 7.333333|    6|        1.572867| 7.333333|  6| 8.333333| 2.333333| 21.86752| -0.2539642| 2.344842| 8.333333| 8.666667|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_lengua_1o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 29.86111
[1] 70.13889
[1] 31.25

### Lengua 2do año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_lengua2 <- datos_lengua_2o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_lengua2 <- datos_lengua2 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_lengua2)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [1,2)                1                 0.001858736
2 [2,3)                9                 0.016728625
3 [3,4)               13                 0.024163569
4 [4,5)               37                 0.068773234
5 [5,6)               73                 0.135687732
6 [6,7)              136                 0.252788104
7 [7,8)              105                 0.195167286
8 [8,9)               92                 0.171003717
9 [9,10]              72                 0.133828996
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.1858736              1
2  1.6728625             10
3  2.4163569             23
4  6.8773234             60
5 13.5687732            133
6 25.2788104            269
7 19.5167286            374
8 17.1003717            466
9 13.3828996            538
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.001858736                     0.1858736
2 0.018587361                     1.8587361
3 0.042750929                     4.2750929
4 0.111524164                    11.1524164
5 0.247211896                    24.7211896
6 0.500000000                    50.0000000
7 0.695167286                    69.5167286
8 0.866171004                    86.6171004
9 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_lengua_2o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar|    Rango| Q1| Q3| RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers                |
|:---|--------:|--------:|----:|---------------:|--------:|--:|--:|---:|--------:|----------:|--------:|---:|--------:|:-----------------------|
|25% | 6.814126| 6.833333|    6|         1.66975| 8.333333|  6|  8|   2| 24.50424| -0.3450022| 2.643842|   8| 8.666667|2.3, 2.7, 1.7, 2.7, 2.7 |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_lengua_2o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 37.91822
[1] 62.08178
[1] 24.90706

### Lengua 3ro año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_lengua3 <- datos_lengua_3o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_lengua3 <- datos_lengua3 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_lengua3)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                2                 0.003984064
2 [3,4)               12                 0.023904382
3 [4,5)               28                 0.055776892
4 [5,6)               51                 0.101593625
5 [6,7)              151                 0.300796813
6 [7,8)               92                 0.183266932
7 [8,9)               81                 0.161354582
8 [9,10]              85                 0.169322709
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.3984064              2
2  2.3904382             14
3  5.5776892             42
4 10.1593625             93
5 30.0796813            244
6 18.3266932            336
7 16.1354582            417
8 16.9322709            502
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.003984064                     0.3984064
2 0.027888446                     2.7888446
3 0.083665339                     8.3665339
4 0.185258964                    18.5258964
5 0.486055777                    48.6055777
6 0.669322709                    66.9322709
7 0.830677291                    83.0677291
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_lengua_3o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar|    Rango| Q1| Q3| RIQ|       CV| Asimetria| Curtosis| P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|--------:|--:|--:|---:|--------:|---------:|--------:|---:|--------:|:--------|
|25% | 6.988048|       7|    6|        1.593215| 7.666667|  6|  8|   2| 22.79915| -0.141606| 2.540638|   8| 8.666667|2.3, 2.7 |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_lengua_3o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 32.27092
[1] 67.72908
[1] 24.9004

### Lengua 4to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_lengua4 <- datos_lengua_4o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_lengua4 <- datos_lengua4 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_lengua4)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                1                 0.00203252
2 [3,4)               11                 0.02235772
3 [4,5)               14                 0.02845528
4 [5,6)               42                 0.08536585
5 [6,7)              123                 0.25000000
6 [7,8)              114                 0.23170732
7 [8,9)               96                 0.19512195
8 [9,10]              91                 0.18495935
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.203252               1
2  2.235772              12
3  2.845528              26
4  8.536585              68
5 25.000000             191
6 23.170732             305
7 19.512195             401
8 18.495935             492
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.00203252                      0.203252
2 0.02439024                      2.439024
3 0.05284553                      5.284553
4 0.13821138                     13.821138
5 0.38821138                     38.821138
6 0.61991870                     61.991870
7 0.81504065                     81.504065
8 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_lengua_4o, "Promedio")

|   Media|  Mediana| Moda| Desvio_Estandar|    Rango|       Q1|       Q3| RIQ|       CV|  Asimetria| Curtosis|      P70|       D8|Outliers  |
|-------:|--------:|----:|---------------:|--------:|--------:|--------:|---:|--------:|----------:|--------:|--------:|--------:|:---------|
| 7.28523| 7.333333|    6|        1.520379| 7.333333| 6.333333| 8.333333|   2| 20.86934| -0.3005634| 2.785484| 8.233333| 8.666667|3, 3, 2.7 |
| 7.28523| 7.333333|    7|        1.520379| 7.333333| 6.333333| 8.333333|   2| 20.86934| -0.3005634| 2.785484| 8.233333| 8.666667|3, 3, 2.7 |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_lengua_4o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.233333

[1] 23.17073
[1] 76.82927
[1] 30.0813

### Lengua 5to = Literatura Latinoamericana

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_lengua5 <- datos_lengua_5o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_lengua5 <- datos_lengua5 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_lengua5)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                2                 0.004938272
2 [3,4)                2                 0.004938272
3 [4,5)               13                 0.032098765
4 [5,6)               26                 0.064197531
5 [6,7)              100                 0.246913580
6 [7,8)               92                 0.227160494
7 [8,9)               87                 0.214814815
8 [9,10]              83                 0.204938272
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.4938272              2
2  0.4938272              4
3  3.2098765             17
4  6.4197531             43
5 24.6913580            143
6 22.7160494            235
7 21.4814815            322
8 20.4938272            405
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.004938272                     0.4938272
2 0.009876543                     0.9876543
3 0.041975309                     4.1975309
4 0.106172840                    10.6172840
5 0.353086420                    35.3086420
6 0.580246914                    58.0246914
7 0.795061728                    79.5061728
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_lengua_5o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar| Rango|       Q1|       Q3|      RIQ|     CV|  Asimetria| Curtosis|      P70| D8|Outliers |
|:---|--------:|--------:|----:|---------------:|-----:|--------:|--------:|--------:|------:|----------:|--------:|--------:|--:|:--------|
|25% | 7.397531| 7.333333|    6|        1.458349|     8| 6.333333| 8.666667| 2.333333| 19.714| -0.4178364| 2.983637| 8.333333|  9|2, 2     |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_lengua_5o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 22.22222
[1] 77.77778
[1] 34.07407

### Lengua 6to = Literatura Argentina

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_lengua6 <- datos_lengua_6o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_lengua6 <- datos_lengua6 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_lengua6)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                2                 0.004807692
2 [4,5)               18                 0.043269231
3 [5,6)               20                 0.048076923
4 [6,7)               99                 0.237980769
5 [7,8)               78                 0.187500000
6 [8,9)               96                 0.230769231
7 [9,10]             103                 0.247596154
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.4807692              2
2  4.3269231             20
3  4.8076923             40
4 23.7980769            139
5 18.7500000            217
6 23.0769231            313
7 24.7596154            416
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.004807692                     0.4807692
2 0.048076923                     4.8076923
3 0.096153846                     9.6153846
4 0.334134615                    33.4134615
5 0.521634615                    52.1634615
6 0.752403846                    75.2403846
7 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_lengua_6o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar|    Rango|       Q1|       Q3|      RIQ|       CV| Asimetria| Curtosis|      P70| D8|Outliers |
|:---|--------:|--------:|----:|---------------:|--------:|--------:|--------:|--------:|--------:|---------:|--------:|--------:|--:|:--------|
|25% | 7.569712| 7.666667|    9|        1.488358| 6.666667| 6.333333| 8.666667| 2.333333| 19.66201| -0.288657| 2.372146| 8.333333|  9|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_lengua_6o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_lengua_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 19.47115
[1] 80.52885
[1] 38.94231

# Calculo de la materia Historia por años:

In [ ]:
# Dividimos el data set de Historia en años:

# Combinar divisiones en una nueva columna
datos_historia_1o <- datos_historia %>%
  filter(curso == "1ro Secundaria") %>%
  mutate(division_agrupada = "1er Año")

datos_historia_2o <- datos_historia %>%
  filter(curso == "2do Secundaria") %>%
  mutate(division_agrupada = "2do Año")

datos_historia_3o <- datos_historia %>%
  filter(curso == "3ro Secundaria") %>%
  mutate(division_agrupada = "3er Año")

datos_historia_4o <- datos_historia %>%
  filter(curso == "4to Secundaria") %>%
  mutate(division_agrupada = "4to Año")

datos_historia_5o <- datos_historia %>%
  filter(curso == "5to Secundaria") %>%
  mutate(division_agrupada = "5to Año")

datos_historia_6o <- datos_historia %>%
  filter(curso == "6to Secundaria") %>%
  mutate(division_agrupada = "6to Año")

### Historia 1er año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_historia1 <- datos_historia_1o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_historia1 <- datos_historia1 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_historia1)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                1                 0.001730104
2 [3,4)                6                 0.010380623
3 [4,5)               22                 0.038062284
4 [5,6)               64                 0.110726644
5 [6,7)              133                 0.230103806
6 [7,8)              109                 0.188581315
7 [8,9)              119                 0.205882353
8 [9,10]             124                 0.214532872
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.1730104              1
2  1.0380623              7
3  3.8062284             29
4 11.0726644             93
5 23.0103806            226
6 18.8581315            335
7 20.5882353            454
8 21.4532872            578
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.001730104                     0.1730104
2 0.012110727                     1.2110727
3 0.050173010                     5.0173010
4 0.160899654                    16.0899654
5 0.391003460                    39.1003460
6 0.579584775                    57.9584775
7 0.785467128                    78.5467128
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_historia_1o, "Promedio")

|    |   Media|  Mediana| Moda| Desvio_Estandar|    Rango| Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70| D8|Outliers |
|:---|-------:|--------:|----:|---------------:|--------:|--:|--------:|--------:|--------:|----------:|--------:|--------:|--:|:--------|
|25% | 7.38466| 7.666667|    6|        1.605959| 7.333333|  6| 8.666667| 2.666667| 21.74724| -0.2016394| 2.372793| 8.333333|  9|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_historia_1o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 25.95156
[1] 74.04844
[1] 33.56401

### Histora 2do año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_historia2 <- datos_historia_2o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_historia2 <- datos_historia2 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_historia2)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                8                 0.01520913
2 [3,4)                8                 0.01520913
3 [4,5)               45                 0.08555133
4 [5,6)               40                 0.07604563
5 [6,7)              129                 0.24524715
6 [7,8)              102                 0.19391635
7 [8,9)              109                 0.20722433
8 [9,10]              85                 0.16159696
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.520913               8
2  1.520913              16
3  8.555133              61
4  7.604563             101
5 24.524715             230
6 19.391635             332
7 20.722433             441
8 16.159696             526
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01520913                      1.520913
2 0.03041825                      3.041825
3 0.11596958                     11.596958
4 0.19201521                     19.201521
5 0.43726236                     43.726236
6 0.63117871                     63.117871
7 0.83840304                     83.840304
8 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_historia_2o, "Promedio")

|    |   Media| Mediana| Moda| Desvio_Estandar| Rango| Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers         |
|:---|-------:|-------:|----:|---------------:|-----:|--:|--------:|--------:|--------:|----------:|--------:|---:|--------:|:----------------|
|25% | 7.04943|       7|    6|        1.693713|     8|  6| 8.333333| 2.333333| 24.02624| -0.3599028| 2.750913|   8| 8.666667|2.3, 2, 2.3, 2.3 |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_historia_2o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 30.98859
[1] 69.01141
[1] 26.9962

### Historia 3er año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_historia3 <- datos_historia_3o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_historia3 <- datos_historia3 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_historia3)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                9                 0.01803607
2 [4,5)               22                 0.04408818
3 [5,6)               56                 0.11222445
4 [6,7)              100                 0.20040080
5 [7,8)              136                 0.27254509
6 [8,9)              108                 0.21643287
7 [9,10]              68                 0.13627255
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.803607               9
2  4.408818              31
3 11.222445              87
4 20.040080             187
5 27.254509             323
6 21.643287             431
7 13.627255             499
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01803607                      1.803607
2 0.06212425                      6.212425
3 0.17434870                     17.434870
4 0.37474950                     37.474950
5 0.64729459                     64.729459
6 0.86372745                     86.372745
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_historia_3o, "Promedio")

|    |    Media|  Mediana|     Moda| Desvio_Estandar| Rango|       Q1|       Q3| RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers   |
|:---|--------:|--------:|--------:|---------------:|-----:|--------:|--------:|---:|--------:|----------:|--------:|---:|--------:|:----------|
|25% | 7.203073| 7.333333| 7.666667|        1.464041|     7| 6.333333| 8.333333|   2| 20.32524| -0.3305836| 2.839191|   8| 8.333333|3, 3, 3, 3 |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_historia_3o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 23.64729
[1] 76.35271
[1] 25.6513

### Historia 4to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_historia4 <- datos_historia_4o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_historia4 <- datos_historia4 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_historia4)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                2                 0.00407332
2 [4,5)               14                 0.02851324
3 [5,6)               43                 0.08757637
4 [6,7)              123                 0.25050916
5 [7,8)              114                 0.23217923
6 [8,9)              122                 0.24847251
7 [9,10]              73                 0.14867617
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.407332               2
2  2.851324              16
3  8.757637              59
4 25.050916             182
5 23.217923             296
6 24.847251             418
7 14.867617             491
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.00407332                      0.407332
2 0.03258656                      3.258656
3 0.12016293                     12.016293
4 0.37067210                     37.067210
5 0.60285132                     60.285132
6 0.85132383                     85.132383
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_historia_4o, "Promedio")

|    Media|  Mediana|     Moda| Desvio_Estandar| Rango|       Q1|       Q3| RIQ|       CV|  Asimetria| Curtosis|      P70|       D8|Outliers |
|--------:|--------:|--------:|---------------:|-----:|--------:|--------:|---:|--------:|----------:|--------:|--------:|--------:|:--------|
| 7.331976| 7.333333| 6.000000|        1.334523|     7| 6.333333| 8.333333|   2| 18.20141| -0.2394001| 2.520053| 8.333333| 8.666667|3        |
| 7.331976| 7.333333| 8.000000|        1.334523|     7| 6.333333| 8.333333|   2| 18.20141| -0.2394001| 2.520053| 8.333333| 8.666667|3        |
| 7.331976| 7.333333| 8.333333|        1.334523|     7| 6.333333| 8.333333|   2| 18.20141| -0.2394001| 2.520053| 8.333333| 8.666667|3        |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_historia_4o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 20.9776
[1] 79.0224
[1] 30.75356

### Historia 5to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_historia5 <- datos_historia_5o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_historia5 <- datos_historia5 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_historia5)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                1                 0.002444988
2 [4,5)                7                 0.017114914
3 [5,6)               27                 0.066014670
4 [6,7)               82                 0.200488998
5 [7,8)               72                 0.176039120
6 [8,9)              116                 0.283618582
7 [9,10]             104                 0.254278729
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.2444988              1
2  1.7114914              8
3  6.6014670             35
4 20.0488998            117
5 17.6039120            189
6 28.3618582            305
7 25.4278729            409
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.002444988                     0.2444988
2 0.019559902                     1.9559902
3 0.085574572                     8.5574572
4 0.286063570                    28.6063570
5 0.462102689                    46.2102689
6 0.745721271                    74.5721271
7 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_historia_5o, "Promedio")

|    |    Media| Mediana|     Moda| Desvio_Estandar|    Rango|       Q1| Q3|      RIQ|      CV|  Asimetria| Curtosis|      P70| D8|Outliers |
|:---|--------:|-------:|--------:|---------------:|--------:|--------:|--:|--------:|-------:|----------:|--------:|--------:|--:|:--------|
|25% | 7.806031|       8| 8.666667|        1.428917| 6.333333| 6.666667|  9| 2.333333| 18.3053| -0.3734149|  2.31628| 8.666667|  9|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_historia_5o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.666667

[1] 14.66993
[1] 85.33007
[1] 46.94377

### Historia 6to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_historia6 <- datos_historia_6o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_historia6 <- datos_historia6 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_historia6)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                5                 0.01201923
2 [4,5)                9                 0.02163462
3 [5,6)               14                 0.03365385
4 [6,7)               89                 0.21394231
5 [7,8)               81                 0.19471154
6 [8,9)               86                 0.20673077
7 [9,10]             132                 0.31730769
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.201923               5
2  2.163462              14
3  3.365385              28
4 21.394231             117
5 19.471154             198
6 20.673077             284
7 31.730769             416
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01201923                      1.201923
2 0.03365385                      3.365385
3 0.06730769                      6.730769
4 0.28125000                     28.125000
5 0.47596154                     47.596154
6 0.68269231                     68.269231
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_historia_6o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar| Rango|       Q1| Q3|      RIQ|       CV| Asimetria| Curtosis| P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|-----:|--------:|--:|--------:|--------:|---------:|--------:|---:|--------:|:--------|
|25% | 7.832532|       8|    9|        1.491789|     7| 6.666667|  9| 2.333333| 19.04606| -0.475267| 2.746675|   9| 9.333333|3, 3     |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_historia_6o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_historia_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  9

[1] 16.10577
[1] 83.89423
[1] 45.19231

# Calculo de la materia Geografia por años:

In [ ]:
# Dividimos el data set de Historia en años:

# Combinar divisiones en una nueva columna
datos_geografia_1o <- datos_geografia %>%
  filter(curso == "1ro Secundaria") %>%
  mutate(division_agrupada = "1er Año")

datos_geografia_2o <- datos_geografia %>%
  filter(curso == "2do Secundaria") %>%
  mutate(division_agrupada = "2do Año")

datos_geografia_3o <- datos_geografia %>%
  filter(curso == "3ro Secundaria") %>%
  mutate(division_agrupada = "3er Año")

datos_geografia_4o <- datos_geografia %>%
  filter(curso == "4to Secundaria") %>%
  mutate(division_agrupada = "4to Año")

datos_geografia_5o <- datos_geografia %>%
  filter(curso == "5to Secundaria") %>%
  mutate(division_agrupada = "5to Año")

datos_geografia_6o <- datos_geografia %>%
  filter(curso == "6to Secundaria") %>%
  mutate(division_agrupada = "6to Año")

### Geografia 1er año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_geografia1 <- datos_geografia_1o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_geografia1 <- datos_geografia1 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_geografia1)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                1                 0.001730104
2 [3,4)                5                 0.008650519
3 [4,5)               17                 0.029411765
4 [5,6)               47                 0.081314879
5 [6,7)              148                 0.256055363
6 [7,8)              132                 0.228373702
7 [8,9)              131                 0.226643599
8 [9,10]              97                 0.167820069
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.1730104              1
2  0.8650519              6
3  2.9411765             23
4  8.1314879             70
5 25.6055363            218
6 22.8373702            350
7 22.6643599            481
8 16.7820069            578
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.001730104                     0.1730104
2 0.010380623                     1.0380623
3 0.039792388                     3.9792388
4 0.121107266                    12.1107266
5 0.377162630                    37.7162630
6 0.605536332                    60.5536332
7 0.832179931                    83.2179931
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_geografia_1o, "Promedio")

|    |   Media|  Mediana| Moda| Desvio_Estandar|    Rango| Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70|       D8|Outliers |
|:---|-------:|--------:|----:|---------------:|--------:|--:|--------:|--------:|--------:|----------:|--------:|--------:|--------:|:--------|
|25% | 7.33564| 7.333333|    6|         1.46017| 7.333333|  6| 8.333333| 2.333333| 19.90514| -0.2478362| 2.600287| 8.333333| 8.666667|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_geografia_1o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_1o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.333333

[1] 25.77855
[1] 74.22145
[1] 32.17993

### Geografia 2do año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_geografia2 <- datos_geografia_2o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_geografia2 <- datos_geografia2 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_geografia2)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                7                 0.01308411
2 [3,4)                9                 0.01682243
3 [4,5)               41                 0.07663551
4 [5,6)               65                 0.12149533
5 [6,7)              124                 0.23177570
6 [7,8)              105                 0.19626168
7 [8,9)              123                 0.22990654
8 [9,10]              61                 0.11401869
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.308411               7
2  1.682243              16
3  7.663551              57
4 12.149533             122
5 23.177570             246
6 19.626168             351
7 22.990654             474
8 11.401869             535
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01308411                      1.308411
2 0.02990654                      2.990654
3 0.10654206                     10.654206
4 0.22803738                     22.803738
5 0.45981308                     45.981308
6 0.65607477                     65.607477
7 0.88598131                     88.598131
8 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_geografia_2o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar| Rango| Q1| Q3| RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers              |
|:---|--------:|-------:|----:|---------------:|-----:|--:|--:|---:|--------:|----------:|--------:|---:|--------:|:---------------------|
|25% | 6.917757|       7|    6|        1.610762|     8|  6|  8|   2| 23.28446| -0.4311039| 2.748108|   8| 8.333333|2.3, 2.7, 2.3, 2, 2.3 |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_geografia_2o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_2o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 34.20561
[1] 65.79439
[1] 24.48598

### Geografia 3er año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_geografia3 <- datos_geografia_3o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_geografia3 <- datos_geografia3 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_geografia3)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)               10                 0.02012072
2 [4,5)               31                 0.06237425
3 [5,6)               55                 0.11066398
4 [6,7)              140                 0.28169014
5 [7,8)              103                 0.20724346
6 [8,9)               98                 0.19718310
7 [9,10]              60                 0.12072435
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  2.012072              10
2  6.237425              41
3 11.066398              96
4 28.169014             236
5 20.724346             339
6 19.718310             437
7 12.072435             497
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.02012072                      2.012072
2 0.08249497                      8.249497
3 0.19315895                     19.315895
4 0.47484909                     47.484909
5 0.68209256                     68.209256
6 0.87927565                     87.927565
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_geografia_3o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar| Rango| Q1| Q3| RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|-----:|--:|--:|---:|--------:|----------:|--------:|---:|--------:|:--------|
|25% | 6.992622|       7|    6|        1.521556|     7|  6|  8|   2| 21.75945| -0.1332304| 2.541978|   8| 8.333333|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_geografia_3o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_3o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 33.1992
[1] 66.8008
[1] 24.14487

### Geografia 4to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_geografia4 <- datos_geografia_4o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_geografia4 <- datos_geografia4 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_geografia4)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [2,3)                1                 0.002024291
2 [3,4)                5                 0.010121457
3 [4,5)               17                 0.034412955
4 [5,6)               47                 0.095141700
5 [6,7)              157                 0.317813765
6 [7,8)              112                 0.226720648
7 [8,9)               77                 0.155870445
8 [9,10]              78                 0.157894737
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  0.2024291              1
2  1.0121457              6
3  3.4412955             23
4  9.5141700             70
5 31.7813765            227
6 22.6720648            339
7 15.5870445            416
8 15.7894737            494
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.002024291                     0.2024291
2 0.012145749                     1.2145749
3 0.046558704                     4.6558704
4 0.141700405                    14.1700405
5 0.459514170                    45.9514170
6 0.686234818                    68.6234818
7 0.842105263                    84.2105263
8 1.000000000                   100.0000000

In [ ]:
calcular_estadisticos(datos_geografia_4o, "Promedio")

|    |    Media| Mediana| Moda| Desvio_Estandar|    Rango| Q1| Q3| RIQ|       CV|  Asimetria| Curtosis| P70|       D8|Outliers |
|:---|--------:|-------:|----:|---------------:|--------:|--:|--:|---:|--------:|----------:|--------:|---:|--------:|:--------|
|25% | 7.105263|       7|    6|        1.438134| 7.666667|  6|  8|   2| 20.24041| -0.0078203| 2.709962|   8| 8.466667|2.3      |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_geografia_4o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_4o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

70%
  8

[1] 28.94737
[1] 71.05263
[1] 23.68421

### Geografia 5to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_geografia5 <- datos_geografia_5o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_geografia5 <- datos_geografia5 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_geografia5)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [4,5)               9                  0.02205882
2 [5,6)              22                  0.05392157
3 [6,7)              86                  0.21078431
4 [7,8)              96                  0.23529412
5 [8,9)              97                  0.23774510
6 [9,10]             98                  0.24019608
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  2.205882               9
2  5.392157              31
3 21.078431             117
4 23.529412             213
5 23.774510             310
6 24.019608             408
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.02205882                      2.205882
2 0.07598039                      7.598039
3 0.28676471                     28.676471
4 0.52205882                     52.205882
5 0.75980392                     75.980392
6 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_geografia_5o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar| Rango|       Q1|       Q3| RIQ|       CV|  Asimetria| Curtosis|      P70| D8|Outliers |
|:---|--------:|--------:|----:|---------------:|-----:|--------:|--------:|---:|--------:|----------:|--------:|--------:|--:|:--------|
|25% | 7.629902| 7.666667|    9|        1.367302|     6| 6.666667| 8.666667|   2| 17.92031| -0.2824594| 2.380898| 8.666667|  9|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_geografia_5o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_5o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.666667

[1] 17.64706
[1] 82.35294
[1] 39.46078

### Geografia 6to año:

In [ ]:
# Ahora creamos una tabla de frecuencias de la materia Lengua en general en la secundaria antes de separarlo por años:

# 1. Definir los intervalos (bins)
breaks <- seq(1, 10, by = 1) # Intervalos de 1 en 1 desde 1 hasta 10

# 2. Crear una nueva columna con los intervalos
datos_geografia6 <- datos_geografia_6o %>%
  mutate(intervalo_promedio = cut(Promedio, breaks = breaks, include.lowest = TRUE,right = FALSE))

# 3. Crear la tabla de frecuencias por intervalos
tabla_frecuencias_geografia6 <- datos_geografia6 %>%
  group_by(intervalo_promedio) %>%
  summarise(Frecuencia_Absoluta = n()) %>%
  mutate(
    Frecuencia_Relativa = Frecuencia_Absoluta / sum(Frecuencia_Absoluta),
    Frecuencia_Porcentual = Frecuencia_Relativa * 100, # Frecuencia porcentual
    Frecuencia_Absoluta_Acumulada = cumsum(Frecuencia_Absoluta), # Acumulada absoluta
    Frecuencia_Relativa_Acumulada = cumsum(Frecuencia_Relativa), # Acumulada relativa
    Frecuencia_Porcentual_Acumulada = cumsum(Frecuencia_Porcentual) # Acumulada porcentual
  )

# 4. Mostrar la tabla de frecuencias por intervalos
View(tabla_frecuencias_geografia6)

  intervalo_promedio Frecuencia_Absoluta Frecuencia_Relativa
1 [3,4)                5                 0.01204819
2 [4,5)                7                 0.01686747
3 [5,6)               31                 0.07469880
4 [6,7)              115                 0.27710843
5 [7,8)               73                 0.17590361
6 [8,9)               88                 0.21204819
7 [9,10]              96                 0.23132530
  Frecuencia_Porcentual Frecuencia_Absoluta_Acumulada
1  1.204819               5
2  1.686747              12
3  7.469880              43
4 27.710843             158
5 17.590361             231
6 21.204819             319
7 23.132530             415
  Frecuencia_Relativa_Acumulada Frecuencia_Porcentual_Acumulada
1 0.01204819                      1.204819
2 0.02891566                      2.891566
3 0.10361446                     10.361446
4 0.38072289                     38.072289
5 0.55662651                     55.662651
6 0.76867470                     76.867470
7 1.00000000                    100.000000

In [ ]:
calcular_estadisticos(datos_geografia_6o, "Promedio")

|    |    Media|  Mediana| Moda| Desvio_Estandar| Rango|       Q1|       Q3|      RIQ|       CV|  Asimetria| Curtosis|      P70| D8|Outliers |
|:---|--------:|--------:|----:|---------------:|-----:|--------:|--------:|--------:|--------:|----------:|--------:|--------:|--:|:--------|
|25% | 7.496385| 7.333333|    6|        1.544274|     7| 6.333333| 8.666667| 2.333333| 20.60025| -0.1535906| 2.317718| 8.666667|  9|         |

In [ ]:
# Respondemos la pregunta C de la actividad 2-guia 2:

quantile(datos_geografia_6o$Promedio, 0.70)

# Respondemos la pregunta E de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas menores a 6
porcentaje <- f_dist(6)  # Calcula la proporción de estudiantes con notas <= 6
print(porcentaje * 100) # Multiplica por 100 para obtener el porcentaje

# Respondemos la pregunta F de la actividad 2-guia 2:

resultado <- abs((porcentaje * 100) - 100)
print(resultado)

# Respondemos la pregunta G de la actividad 2-guia 2:

# Calcular la función de distribución empírica acumulada
f_dist <- ecdf(datos_geografia_6o$Promedio)

# Obtener el porcentaje de estudiantes con notas mayores a 8
porcentaje <- 1 - f_dist(8)
print(porcentaje * 100)

     70%
8.666667

[1] 24.09639
[1] 75.90361
[1] 37.83133